<?php

/**
 * @file
 * Provides functions and hook implementations for webform multiple file module.
 */

/**
 * Value for field API indicating a field accepts an unlimited number of values.
 */
define('WEBFORM_MULTIPLE_FILE_CARDINALITY_UNLIMITED', -1);

/**
 * Implements hook_webform_component_info().
 */
function webform_multiple_file_webform_component_info() {
  $components = array();

  webform_component_include('file');

  $components['multiple_file'] = array(
    'label' => t('Multiple file'),
    'description' => t('Multiple file upload support for webform.'),
    'features' => array(
      'conditional' => FALSE,
      'attachment' => TRUE,
    ),
    'file' => 'webform_multiple_file.webform.inc',
  );

  return $components;
}

/**
 * Implements hook_webform_submission_presave().
 *
 * @see webform_webform_submission_presave()
 */
function webform_multiple_file_webform_submission_presave($node, &$submission) {
  $has_file_components = FALSE;
  $new_fids = array();
  $old_fids = array();

  foreach ($node->webform['components'] as $cid => $component) {
    if ($component['type'] == 'multiple_file') {
      $has_file_components = TRUE;
      if (!empty($submission->data[$cid]['value'])) {
        $new_fids = array_merge($new_fids, $submission->data[$cid]['value']);
      }
    }
  }

  if ($has_file_components) {
    // If we're updating a submission, build a list of previous files.
    if (isset($submission->sid)) {
      $old_submission = webform_get_submission($node->nid, $submission->sid, TRUE);

      foreach ($node->webform['components'] as $cid => $component) {
        if ($component['type'] == 'multiple_file') {
          if (!empty($old_submission->data[$cid]['value'])) {
            $old_fids = array_merge($old_fids, $old_submission->data[$cid]['value']);
          }
        }
      }
    }

    // Save the list of added or removed files so we can add usage in
    // hook_webform_submission_insert() or _update().
    $submission->file_usage = array(
      // Diff the old against new to determine what files were deleted.
      'deleted_fids' => array_diff($old_fids, $new_fids),
      // Diff the new files against old to determine new uploads.
      'added_fids' => array_diff($new_fids, $old_fids),
    );
  }
}
